### ISSUE TITLE
Typos in the readme

### ISSUE THREAD

**Issue by hanselowski** [facebookresearch/PAQ#5]
Hi team,
Thanks a lot for sharing the code and the pretrained models!
It looks like there is the same typo at two lines in the readme:
python -m paq.download -v -n models.rerankers.**retriever**_multi_xxlarge
--> python -m paq.download -v -n models.rerankers.**reranker**_multi_xxlarge

**Comment by patrick-s-h-lewis** [comment]
Thanks for the spot, pushing fix now
